### ISSUE TITLE
Having trouble running "make" command

### ISSUE THREAD

**Issue by tarunaaggarwal** [sequencing/NxTrim#10]
Hi,

I'm having trouble running the "make" command for NxTrim. When I run this command, I get the following error message. 

/usr/bin/ld: cannot find -lboost_program_options
collect2: error: ld returned 1 exit status
make: *** [mergeReads] Error 1

I don't know how to fix it as I'm very new to programming. Please advice. Thanks!

-Taruna

**Comment by jaredo** [comment]
Hi Taruna,

You need to have the [boost libraries](http://www.boost.org/) installed on your system and set the BOOST_ROOT environment variable appropriately.  See [here](https://github.com/sequencing/NxTrim#installation).

I appreciate building boost can be a pain, perhaps a solution is for me provide some pre-compiled nxtrim binaries on here.  What operating system are you using?

best,

Jared

**Comment by tarunaaggarwal** [comment]
Hi Jared,

Thank you for your reply. I'm using MacOSX (10.10.2) and I did run the boost codes on your NxTrim site, but I got nowhere. I'm sorry if that's too vague. I'm just so new that I'm not helpful perhaps. I will read the info about boost libraries you sent me. Please let me know if you need additional information from me. Thanks!

-Taruna

**Comment by tarunaaggarwal** [comment]
Hi Jared,

I forgot to tell you that I'm trying to run NxTrim on a "super computer" through my school which I can access via terminal. I think that changes the whole reason why I can't install Boost libraries, doesn't it? Regardless, I installed NxTrim on my own computer and tried to run it, but I got a similar message.

g++ -Wall -g -I/usr//include -c fastqlib.cpp
In file included from fastqlib.cpp:1:
In file included from ./fastqlib.h:2:
./utilityfunc.h:10:10: fatal error: 'boost/iostreams/filtering_stream.hpp' file
      not found
#include <boost/iostreams/filtering_stream.hpp>
         ^
1 error generated.
make: *** [fastqlib.o] Error 1
Tarunas-MacBook-Pro:NxTrim Taruna$ ./nxtrim
-bash: ./nxtrim: No such file or directory
 
Sorry for the trouble, but I appreciate your help!

-Taruna

**Comment by tarunaaggarwal** [comment]
Hi Jared,

It's working now. One of my advisors suggested that I run the following command and it worked! 

export BOOST_ROOT=/usr
make

Thank you for your help though! I appreciate it! 

Best,
Taruna
