### ISSUE TITLE
differing lengths

### ISSUE THREAD

**Issue by jvollme** [sequencing/NxTrim#12]
Hi,
I want to use NxTrim on a Illumina Nextera Mate Pair dataset generated by a Miseq machine (with 300bp read lengths because it was multiplexed with some TruSeq libraries). 
Probably due to somewhat non-uniform insert lengths and consistenly  worse quality values for the reverse reads, I get reads with differing read lengths.

When I run NxTrim, the program aborts with the warning ```WARNING: reads with differing lengths. Has this data already been trimmed?```

So i have some questions about this:

-Does this mean I have to trim and filter the reads to a uniform length before I can use NxTrim?

-Do only the respective forward and reverse reads of each pair have to be uniform in length or do ALL reads have to be uniform in length?

-Is there some kind of narrow tolerance range for insert size differences, and if yes: what is it?

**Comment by jaredo** [comment]
hmm...this warning is expected when there are varying read lengths, but does not cause NxTrim to abort.  It is just there as a precaution so users do not accidentally trim reads twice!

Possibly there is some other bug causing a premature exit.  Could you provide a small reproducible example?

As for insert sizes, nxtrim makes no assumption on insert sizes and these should not affect anything.

**Comment by jvollme** [comment]
Hmm, thats good, because differing read sizes will be a frequent "problem" in our sequencing data. Rerunning this with a reduced dataset (and trimmed to minimum readlength of 150, just to make sure) now gives this result:
```Segmentation Fault```
I have a local installation of boost (v 1.57 as far as i can remember) on our servers, as i do not have admin rights and the globally installed version seems to be older (or does not include all modules needed by make for Nxtrim).  Nxtrim compiled without error messages, but could this still be the problem (as you state that you use boost 1.55)?

I have some problems installing boost 1.55 on my personal system (I have ubuntu were the latest version in the repositories seem to be boost v.1.54). Do you think Ntrix should work with boost v.154?

How should I upload example data for reproduction? Can you provide an upload link or should i prepare a temporary download-link in dropbox?

**Comment by jaredo** [comment]
I don't think that the boost version is the culprit as the boost functions nxtrim uses are quite stable.

Can I just check that you are using the current commit of nxtrim? 8bb986b0bb15dd7dc6608c3002bfedf531dc34e6

There have been a number of bugfixes (at least one relating to read length) since the v3.0.0 release which might fix the issue.

If you can reproduce the example on a single read pair, then you can paste the fastq lines directly into this thread.

cheers,

Jared

**Comment by jvollme** [comment]
I am using NxTrim v.0.3.2-alpha, which is the current one provided when cloning your git repository.

I tried NxTrim on just two read pairs (two forward and two reverse reads).
Now it does seem to trim, but it still ends in "Segmentation Fault"

here is the command with the complete output:
```
~/tools/NxTrim/nxtrim -1 example_for.fastq -2 example_rev.fastq --output-prefix test

NxTrim v0.3.2-alpha 

Trimming:
R1:	example_for.fastq
R2:	example_rev.fastq
Output: test.*.fastq.gz
WARNING: reads with differing lengths. Has this data already been trimmed?

Trimming summary:
2 / 2	( 100.00% )	reads passed chastity/purity filters.
0 / 2	( 0.00% )	reads had TWO copies of adapter (filtered).
0 / 2	( 0.00% )	read pairs were ignored because template length appeared less than read length
2 remaining reads were trimmed

0 / 2	( 0.00% )	read pairs had MP orientation
2 / 2	( 100.00% )	read pairs had PE orientation
0 / 2	( 0.00% )	read pairs had unknown orientation
0 / 2	( 0.00% )	were single end reads

1 / 2	( 50.00% )	extra single end reads were generated from overhangs
Segmentation fault
```
The outputfiles (test.*.fastq.gz) are all empty.

here are the input sequences:
First the forward reads:
```
@M03384:36:000000000-AG2VL:1:1101:21146:4829 1:N:0:5
GAAGCGATGATCCACCCCGCCACCCTGGCCGACCTGCCGCAGCTGGGCGCCGATATCCTCAAGGGCCAGGTCCGGGGCCGCGTGGTCGTCGACGTGAACGCCTGACCCGATCCCGGATCCGGGCCGCGACGTGCTGCGACCGGTCGGGATCCAGGGTCGCAAGGACCAAATATATCAAAACCGTCAAAAACTTGTCGGTTTTGACCGAAAAACCGCCTCGCCCGGTTGGGTTCACCTGCCGACCTGCGCTATCCTGTCGCCATTCGACCCCGTATCACCGTCAATTCACC
+
CCCCCGGGGGFFGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGDEGGGGGGGGGGGFGGGGGGCEGG?FGGGGGGGGDGCFGGGGGFGGGGFFGGGGGGG5C<CGGGGGGGDGEGGF*2+<CCEEGG5E=DGGGGF>=BCC:DFEF5*?CFFFFFEGG0>5F@DGE>FC77<E8C*;C9:C?DEF358>=:=4:5241C49A*)5
@M03384:36:000000000-AG2VL:1:1101:14034:4830 1:N:0:5
AAGCGCAGAAATGGATCAGCAGGAACGTTTTCTTCGCCGTCTTCCGGAAAGGCGAATTGATGATAACTGTCCGCAATGATGTCGGACGCCTCTACCTGAACATTTTCCCCGATCACGATGGGATTATCAGAGGAAATCAGAAGCGGCTCGGTCATCGACAGGCGCAGTAGCACGGGATCCAACGTCACACCGGTCGCATTAGCGGCGTCCACGTCATCCGCGATAACAACCGCGCGCGGTTCACCCCAGATG
+
-8AC,@FGGGGGGGGGGGGGGGGGGGGCFGEF@FFGGGGGGGGGGGGGGGGGGGEGGGFGFGFGGGGGFGFGGGGGGGFGGGGFGGGGGGGGGGGGGGGGGGGGGGGGFGGFGGGGGGGGGGGGFGDFGGDGFGGGGGGGGGGGGGGGGGGFGDGGGFGGGGGGGGGEGGCFGGGGGGGGCFGGGGGGGGGGGGGDGGEGCGGGGGGGE1>FGCCGGGGE8>?3CEFGFFDEE)788?5>5CFFFF9:BG+:
```
then the reverse reads:
```
@M03384:36:000000000-AG2VL:1:1101:21146:4829 2:N:0:5
CACCCACCAGCTGATCGACGCGCTGGGACTGGCCGAAACCTGTCTCTTATACACATCTAGATGTGTATAAGAGACAGCCGTACAGCTTCGCCTGGTCGGCGGCGCATTGCAGCGCTTTTTGCAACTTGTCCGCGTGGACGAGGTCCACGGGGCACATGATTTTCCGGAACACGGGCACTCCTTCCTGTCACACGCGCGGCCCG
+
CCCCCGGGGGEFGGGGGGGGGGGGGGEGGGEFFGGGGGGGGCFGDEFGGGGGGFGGGFFG9EGGGGGGGGGGGGGGGGFGGGGEGGGCFFGGGGGEFGECFGGGCFFE,:<FFGEGGGFFEFAFGGGFGGGGGCFEE7EB>CEFGDG,>E595CGGGG79==BDGGE:DGFC8>ECAEAFFGA;FG7C?9?@G5C2891>14<
@M03384:36:000000000-AG2VL:1:1101:14034:4830 2:N:0:5
ACATCTAGATGTGTATAAGAGACAGCTTATGCCTGCCTGTTTGGTGACAACCACCTGGTCATCTGGGGTGAACCGCGCGCGGTTGTTATCGCGGATGACGTGGACGCCGCTAATGCGACCGGTGTGACGTTGGATCCCGTGCTACTGCGCCTGTCGATGACCGAGCCGCTTCTGATTTCCTCTGATAATCCCATCGT
+
CCCCC9EF@FEFFEEEDGGFGGGGG<FFCF,CEGG8FGGGGGFGG8F,<CECFGGGGGGGGGGGGGGGGGFFGGDGGGGGGGGEGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGEGGGGGEGGGFGGGGGG6:DGGCGDGGGFFGGGGGGGGGGFGGGGGGGGGFF<CDE8:@CFE9C;3@CFFGGG7@E6C8(=
```

Thanks for helping. It would be really great to get this tool running on our system!

**Comment by jaredo** [comment]
I'm sure we can get it working!

I found nxtrim actually runs okay on your example.  Perhaps our versions of the software are not quite the same, I have updated the versioning such that the git commit hash is now in the version number.  The version should now read `NxTrim v0.3.2-alpha-8bb986b` for the latest commit.

I have also added you example to the repository under example/issue12_R?.fastq.gz.  Could you try the following?

```
git pull 
make
./nxtrim -1 example/issue12_R1.fastq.gz -2 example/issue12_R2.fastq.gz  -O /tmp/test
```

and see if it works?

thanks,

Jared

**Comment by jvollme** [comment]
Hi jared,
I tried rerunning the example after pulling and compiling zhe latest commit as per your instructions.
The version now reads "NxTrim v0.3.2-alpha-8bb986b" as it should.

However i still get a "Seqmentation fault" when running the tool:
```
>./nxtrim -1 example/issue12_R1.fastq.gz -2 example/issue12_R2.fastq.gz  -O /tmp/test

NxTrim v0.3.2-alpha-8bb986b

Trimming:
R1:	example/issue12_R1.fastq.gz
R2:	example/issue12_R2.fastq.gz
Output: /tmp/test.*.fastq.gz
WARNING: reads with differing lengths. Has this data already been trimmed?

Trimming summary:
2 / 2	( 100.00% )	reads passed chastity/purity filters.
0 / 2	( 0.00% )	reads had TWO copies of adapter (filtered).
0 / 2	( 0.00% )	read pairs were ignored because template length appeared less than read length
2 remaining reads were trimmed

0 / 2	( 0.00% )	read pairs had MP orientation
2 / 2	( 100.00% )	read pairs had PE orientation
0 / 2	( 0.00% )	read pairs had unknown orientation
0 / 2	( 0.00% )	were single end reads

1 / 2	( 50.00% )	extra single end reads were generated from overhangs
Segmentation fault
```

So this seems to be something about my system or specific compilation? Do you have precompiled binaries that should work with 64bit linux systems that i could try instead of compiling myself?

here is the output from ```make```
```
>make
g++ -O3  -I/home/jov14/lib/include -c fastqlib.cpp
g++ -O3  -I/home/jov14/lib/include  mergeReads.cpp fastqlib.o utilityfunc.o -o mergeReads   /home/jov14/lib/lib/libboost_iostreams.a /home/jov14/lib/lib/libboost_program_options.a -lz
g++ -O3  -I/home/jov14/lib/include -c matepair.cpp
g++ -O3  -I/home/jov14/lib/include nxtrim.cpp fastqlib.o utilityfunc.o matepair.o -o nxtrim  /home/jov14/lib/lib/libboost_iostreams.a /home/jov14/lib/lib/libboost_program_options.a -lz
```

here are some infos on the OS running on our servers:
```
>lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.6 (Santiago)
Release:	6.6
Codename:	Santiago
```

**Comment by jaredo** [comment]
Really weird.  I have put the code through valgrind and there are no memory access issues.  Could you try running the same thing using the following static build?

https://dl.dropboxusercontent.com/u/15887058/NxTrim.v0.3.2-alpha-177318b.tar.gz

**Comment by jvollme** [comment]
Thanks for the binaries!  
Now these binaries seem to work on my local system (running ubuntu 14.04,, but where I, however, seem to have messed up the boost libaries and are unable to compile the source code). The test data was processed without running into a segmentation fault. I'll confirm this by processing the complete dataset,a s soon as i have downloaded it onto my system.

However, on our servers (where the boost libraries SHOULD be present as a local installation) the binaries do not work:
```
./nxtrim -1 example/issue12_R1.fastq.gz -2 example/issue12_R2.fastq.gz  -O /tmp/test
./nxtrim: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./nxtrim)
```
probably something about this build not being compatible with our server linux system? Or something about the local boost installation? I would really need that tool more on the servers than on my local system.

**Comment by jaredo** [comment]
Hello! This error is because that binary is compiled against a newer version of glibc. Here is a version where I statically linked glibc which should (I hope) work on your system:

https://dl.dropboxusercontent.com/u/15887058/nxtrim.v0.3.2-alpha-177318b.static.tar.gz

This segmentation fault is very strange.  Is it possible that the boost libraries being linked to were compiled with a different version of gcc to the one you are using to compile NxTrim?

**Comment by jvollme** [comment]
Ah, good point with the gcc version. Maybe gcc has been updated on the server by the admin since i compiled my local versions of the boost-libraries there? Anyway, i recompiled the boost_libraries, then recompiled NxTrim using the recompiled boost_libraries and now it seems to work!
I am sure I'll be able to fix the boost libraries on my personal system too, in order to be able compile future versions of NxTrim on both, the server and my personal system.

Really glad to be able to use that tool now, it seems really useful!

PS: Maybe it could be a good Idea to offer downloads for precompiled binaries for the most widespread systems (such as 64bit and 32bit debian based linux systems) at least for each major release of NxTrim, in order to avoid similar compilation issues for other people?

Anyway, thanks again!

**Comment by jaredo** [comment]
Glad to hear it is working.  I think releasing pre-compiled binaries is also a good idea, will do this with the next release.

I also have plans to remove the boost dependency since it is a pain to build boost.

best,

Jared
