### ISSUE TITLE
ABySS

### ISSUE THREAD

**Issue by sklages** [sequencing/NxTrim#13]
Hi,

any experience in using the output data with abyss? E.g. what best to take as MP and/or PE data for assembly?

**Comment by jaredo** [comment]
I don't have any experience with ABySS. From my (limited) understanding, ABySS can assemble from paired ends and then scaffold with a long insert library. 

Do you have a separate PE library in addition to your Nextera MP library? In that case, I think you would assemble using the PE library and then scaffold using the MP library.  Using the ``--justmp`` flag will generate as many mate-pairs as possible which could then be fed to the ABySS scaffolder.

**Comment by sklages** [comment]
thanks for the fast response. That's what I thought too. I do have separate PE libs (2).
