### ISSUE TITLE
Are only the "mp" reads reverse complemented by default? Or all reads?

### ISSUE THREAD

**Issue by jvollme** [sequencing/NxTrim#16]
From your README.md:

"The trimmer will reverse-complement the reads such that the resulting libraries will be in Forward-Reverse orientation, this reverse-complementing can be disabled via the --norc flag"

This (reverse complementing of mate-pairs) is actually the preferred behaviour for me, but this ONLY concerns the "mp" and possibly "unkown" datasets right? Or are all reads reverse complemented (meaning that the "pe" dataset is now in the incorrect orientation and i have to reverse-complement it back again?

Your examples do not quite resolve this question (actually they confuse me even more):
-Velvet ONLY accepts FR orientation. In your example, you give velvet all pe and mp libraries without any further modification, so I would assume that both are nor in "FR" orientation (meaning that the "mp" reads were reverse-complemented and the "pe" reads were not. Only the "unkown" reads are given with the "shortMatePair" argument, indicating that they may be contaminated with some read pairs in the RF orientation. So far so good...

-SPAdes however, assumes that any mate-pair libraries that you pass on the command line are in the "RF" orientation. In your example you pass the mp reads from nxtrim without  using the --norc argument. Therefore the mp reads should actually be in "FR" orientation and therefore incorrect for SPADES (using your example command).

**Comment by jaredo** [comment]
Apologies for the confusion, the documentation should indeed be improved.

The short answer is, by default, nxtrim will try its best to give you forward-reverse reads in all cases.

How it does this is of course a bit messy. The default behaviour is:
* MP/unknown are reverse complemented 
* PE are not reverse complemented.

The `--norc` command actually does the exact opposite as the above meaning all reads will be RF. This is admittedly pretty stupid behaviour and I will change it `--RF` in future versions.

Regarding SPAdes, the `--hqmp1` command assumes reads are in FR, so the command is correct. This behaviour was changed (from assuming RF) in SPAdes-3.5.0 which might be causing your confusion. See their Changelog:

http://spades.bioinf.spbau.ru/changelog.html

**Comment by jvollme** [comment]
Ah, ok thankyou. Sorry, obviously I was looking at an not up-to-date SPAdes documentation
