### ISSUE TITLE
specify mp/unknown only with `--stdout`

### ISSUE THREAD

**Issue by jaredo** [sequencing/NxTrim#20]
We need to be able to pipe definite MP reads to stdout for some applications. For example, piping them directly to bwa for alignment prior to scaffolding.

As discussed in #18

**Comment by sklages** [comment]
What do you think about adding a switch to decide wether `--stdout` writes just **mp** or a "combined stream" with **mp/unknown** (as it does atm)?

**Comment by jaredo** [comment]
Yes, this is what I am thinking.  I will add flags like:

```
--mp: only output mate-pair reads
--unknown: only output unknown reads
```

**Comment by sklages** [comment]
... which may work combined?
`--mp --unknown`

**Comment by jaredo** [comment]
Yes, but I think mp+unknown would be the default behaviour. Some care is required here though. Do I include a `--pe` flag? And `--se` is a no-go for streaming because it will break the pairing.

More generally, I need to re-work the command line arguments a bit because they have become unclear. NxTrim started as a very specific use-case - frugal trimming of reads to support assemble from relatively low coverage data. Extra functionality has been tacked on post-hoc.

**Comment by sklages** [comment]
mp+unknown as default, yes, that's probably better.

``--pe`` as additional flag? Why not, could be helpful in some situations.

NxTrim is doing a great job, thanks and thumbs up for your work!

**Comment by jaredo** [comment]
I am glad it is useful. I think I can take a look at this next week.

**Comment by jaredo** [comment]
I have just added the options `--stdout-mp`  and  `--stdout-un`. I believe the former will do what you want for scaffolding (pipe the guaranteed mate-pairs to stdout).

**Comment by sklages** [comment]
And `--stdout` dumps unknown+mp?

Great, thanks :-)

**Comment by jaredo** [comment]
>And --stdout dumps unknown+mp?

Yes exactly.
