### ISSUE TITLE
--norc to let output file keep the RF orientation as input file?

### ISSUE THREAD

**Issue by wangyugui** [sequencing/NxTrim#23]
How to let output file keep the RF orientation as input file?

if "--norc" option can do this, we need update the help?
--norc  do NOT reverse-complement mate-pair reads (use this if your reads are already in FR orientation)

nxtrim is a filter application, so we should keep the orig orientation by default like most of filter application?

**Comment by jaredo** [comment]
I have changed the `--norc` flag to `--rf` which I think is less confusing. The functionality is the same. Using `--rf` will return reads in RF orientation (assuming that was there original orientation).

If you can point me to where the documentation still mentions `--norc` I will correct this. Thanks!

>nxtrim is a filter application, so we should keep the orig orientation by default like most of filter application?

This depends on your goal. I assume most people want to use the output in an assembler like SPAdes or Velvet. [See here](https://github.com/sequencing/NxTrim/wiki/Bacterial-assemblies-using-Nextera-Mate-pairs). These software assume FR orientation so NxTrim aims to do this.
