### ISSUE TITLE
Other adaptor clipping after nxtrim ?

### ISSUE THREAD

**Issue by ptranvan** [sequencing/NxTrim#24]
So nxtrim just clipped the biotin adaptor right ?

But there are still the illunima sequencing adaptors (P1 and P2) from which the reads have been sequenced ?

So do we need to reperform an adaptor trimming (with trimmomatic for instance) or nxtrim is sufficient ??

**Comment by jaredo** [comment]
It will clip the P1/P2 sequencings adapters when the fragment is shorter than the read length. 

eg. 

This case is handled:
```
R1 ---------------->
   ======****===~~~
``` 
where `=` is organism DNA, `***` is the Nextera adapter and `~` is the P2 adapter. The `~~~` wil be clipped.

This case is *not* handled:
```
R1 ---------------->
   ~~~======****===
``` 
in practice I don't see the latter, but your mileage may very of course.
