### ISSUE TITLE
Any experience with ALLPATHS-LG assembler ?

### ISSUE THREAD

**Issue by ptranvan** [sequencing/NxTrim#27]
Hi,

Did you have any experience with ALLPATHS-LG assembler ?

What command do you recommend for nxtrim for that assembler ?

**Comment by jaredo** [comment]
I have not run ALLPATHS-LG personally, but as I understand, it requires both long-insert and short-insert libraries. I guess you could run something like the below to generate the long-insert library for scaffolding:

```
nxtrim  -1 EcMG1_R1.fastq.gz -2  EcMG1_R2.fastq.gz -O EcMG1 --justmp
cat EcMG1.unknown.fastq.gz EcMG1.mp.fastq.gz > EcMG1.allmp.fastq.gz
```
