### ISSUE TITLE
Doubt with --justmp

### ISSUE THREAD

**Issue by edu3716** [sequencing/NxTrim#28]
Hi,

I'm pre-processing a Nextera MP library with NxTrim. Each raw read file has ~51M reads. 

(a) If I run NxTrim with --separate, I obtain 7 .gz files (2 mp, 2 unknown, 2 pe and 1 se). My aim is to keep only the 2mp and 2 unknown(unk). So I concatenate them in 1mp1unk and 1mp1unk. FastQC tells me that there are ~34M (~19+14) in each file. The quality is more or less similar to raw data (although I observe that mp seem to be a little bit better than unknown(?)).

(b) Apart, if run the mode --justmp, the output are only 2mp and 2 unk (without pe & se, as expected). Then, if I concatenate mp and unk, should I expect the same amount of reads than with the previous process (i.e. ~34M)? From my understanding yes, but it is not the case: the number is ~51M (a little bit lower than the raw file). Concretely, the file that surprised me was the mp one, that have (~36M reads instead of ~19 as in the above pre-processing). In the case of unknown file, the counts are exactly the same as above. Looking into detail the mp file, I observed that the qualities according to FastQC are extremely low, and when checking the file with zcat I observed a huge amount of reads masked (?) with N. Are that reads with N the pe and se ones, that instead of being removed are kept as masked?

So, after all, if I want to get a file with mp and pe, which way do you recommend? run the program normally and then concatenate mp & unk (i.e. above case) or do --justmp and also concatenate the mp & unk (bottom case). My aim is to use MP for scaffolding because I have a PE library apart, but I also need it for the assembly process mainly because programs such as SPAdes, as far as I know, use MP data also for contig reconstruction apart from scaffolding.

Thanks,

Edu

**Comment by jaredo** [comment]
Hi Edu,

This is expected behaviour. There are certain read pairs that can be either MP *or* PE. 

Consider this:
```
R1 ---------====--------------------
R2 ------------------------------------
```
where `====` is my adapter. Now I can either do make PE by keeping the R1 sequence on the right of the adapter, or I can make an MP by keeping the sequence on the left of the adapter. The default behaviour is the take the orientation which provides the most sequence, in the above example that would be the PE.

Now if you turn on `--justmp` it will always keep the MP orientation, regardless of how much sequence it provides. Hence you end up with more MP pairs.

Does that make sense?

For your scaffolding purposes, and for assembling with SPAdes, you wish to run with `--justmp`.

**Comment by edu3716** [comment]
Ok jaredo, very clear!! Only two more fast questions:

(a) Then, after --justmp, what do you recommend: to use also the unknown or only the mp?
(b) And after NxTrim, do you recommend to use a further filtering (e.g. quality filters or minimum length to avoid very short reads e.g. <25bp). And related with this, why FastQC warns about the low quality of the --justmp output? Is because there are a lot of Ns? Are SPAdes and other conventional assemblers (e.g. Velvet) able to lead with that noise?

Thanks again,

Edu

**Comment by jaredo** [comment]
a) For scaffolding probably use mp, for assembly use unknown and mp. 

b) I never apply any additional filtering/trimming, but your mileage may vary. SPAdes has a very sophisticated error corrector which I trust over adhoc filtering. FastQC is probably complaining due the large number of Ns generated by trimming with `justmp`.

See https://github.com/sequencing/NxTrim/wiki/Bacterial-assemblies-using-Nextera-Mate-pairs for assembly examples.
