### ISSUE TITLE
Program crash with "Assertion `dna.size()==qual.size()' failed."

### ISSUE THREAD

**Issue by aersoares81** [sequencing/NxTrim#30]
Hi, I've been using NxTrim for a while, and never saw this happen before:

`nxtrim: fastqlib.cpp:30: int fqread::set(std::string, std::string, std::string, std::string): Assertion `dna.size()==qual.size()' failed.`

Is there something wrong with the sequencing files? Or is it just a bug? Thanks!

**Comment by jaredo** [comment]
>Is there something wrong with the sequencing files? Or is it just a bug? Thanks!

Hard to say because my error message is very uninformative.

I have just pushed a small change to master that will better describe the error. Can you pull the latest commit, re-compile and run it again? The error message will now print out the problematic fastq entry and we can see if it is a bug or a problem with the input.

best,

Jared

**Comment by aersoares81** [comment]
I'm doing it right now, thanks for the super fast reply!!

**Comment by aersoares81** [comment]
I see what happened now:
```

HWI-ST1293:232:HBBJ1ADXX:1:1105:15491:89448 1:N:0:CTTGTA
GGAGAAGGATGCAGGAAAGAACTCTGCTTACCATTTGCATCCTGGTTTCTCAGTGC
+
CCCFFFFFHHHHHJJJJJFHIJJJJJJJJJJJJIJJJJJJJJJJIJJJJJJJJJJJJJJIJJJJJJJJJJJJJJHHHHFFFFFFDEEDDDDDDDDDDDDED
ERROR: base length was not equal to qual length in read
```
That's so weird, I've never seen that before.

**Comment by jaredo** [comment]
That is new to me. Is the second text box your input fastq? Was any pre-processing applied?

**Comment by aersoares81** [comment]
No pre-processing at all, but I'll check with the processing facility, it's likely they concatenated broken fastq files. Thanks for the nicer error message, and for looking at that so fast!
