### ISSUE TITLE
Shutdown a false WARNING or improve the message/code

### ISSUE THREAD

**Issue by mmokrejs** [sequencing/NxTrim#39]
In issue #34 you said:

> Nxtrim expects external adapter reads to already be removed. This is usually done by default in the fastq conversion software or there are other tools available eg. trimmomatic/cutadapt.

Here is what I get with nxtrim v0.4.1-6d91d55:

```
nxtrim -s .7 -w -1 HFYJ5AFXX.1_5kb_R1.trimmomatic.SE.fastq -2 HFYJ5AFXX.1_5kb_R2.trimmomatic.SE.fastq -O HFYJ5AFXX.1_5kb.trimmomatic.nxtrim --separate --preserve-mp --rf

...

Output: HFYJ5AFXX.1_5kb.trimmomatic.nxtrim.*.fastq.gz
Trimming:
R1:     HFYJ5AFXX.1_5kb_R1.trimmomatic.SE.fastq
R2:     HFYJ5AFXX.1_5kb_R2.trimmomatic.SE.fastq
--preserve-mp is on: will favour MPs over PEs
WARNING: reads with differing lengths. Has this data already been trimmed?
readlength < minlenght
readlength < minlenght
readlength < minlenght
readlength < minlenght
....
readlength < minlenght
readlength < minlenght
readlength < minlenght
READ PAIR 20000
readlength < minlenght
readlength < minlenght
readlength < minlenght
readlength < minlenght
...
Trimming summary:
20662 / 20662   ( 100.00% )     reads passed chastity/purity filters.
0 / 20662       ( 0.00% )       reads had TWO copies of adapter (filtered).
2012 / 20662    ( 9.74% )       read pairs were ignored because template length appeared less than read length
18650 remaining reads were trimmed

11631 / 18650   ( 62.36% )      read pairs had MP orientation
2415 / 18650    ( 12.95% )      read pairs had PE orientation
589 / 18650     ( 3.16% )       read pairs had unknown orientation
4015 / 18650    ( 21.53% )      were single end reads

2755 / 18650    ( 14.77% )      extra single end reads were generated from overhangs
```
Are you sure the previous, Illumina P1/P2 adapter removing step did not cause any problems?

**Comment by jaredo** [comment]
I have improved the message code:

```
 ./nxtrim -1 r1.fq -2 r2.fq -O test
Output: test.*.fastq.gz
Trimming:
R1:	r1.fq
R2:	r2.fq
WARNING: reads with differing lengths. Has this data already been trimmed?
WARNING: read with length < minimum length (21). Will discard this read pair:
@M903:194:000000000-A5FBD:1:1101:20691:2534 1:N:0:ATGTCA
AGTATCAGTTCCA
+
BBBBBFFFBFFFG
@M903:194:000000000-A5FBD:1:1101:20691:2534 2:N:0:ATGTCA
TGCTGTTGTTATAAATACAGTGAATGTAATGTGTCTGCGCATTTAAATTAAAACTCCTGTAATAATGATAAATAACGCAGAAACATATTGTTAATATATGTTATGCACTGTTTGCGATGAGATTGATTAAGACCTGTCTCTTATACACATC
+
111>13@1B>3@333A3F11B113B3D33D3D3DBA110A0EAGG212D1111ABFGG1B2A222D222221B2EE/A///01B0F1FGDGGB2F2B2FFBG2G1FBGHHGHHFFE?H?111FGBGFGD111B0F0FHHGHH1>GF2B11B
```

>Are you sure the previous, Illumina P1/P2 adapter removing step did not cause any problems?

We haven't seen issues in the past.  This warning is saying you have provided some reads with very small length (less than the default min of 21).

**Comment by mmokrejs** [comment]
```
-WARNING: reads with differing lengths. Has this data already been trimmed?
+INFO: Reads with differing lengths. Supposedly this data already trimmed.
```

The second "WARNING" is more a surprise. Why don't you convert this read pair into a single-ended read instead?

Also, it seems it complains about both input read <21nt and about such short reads after your trimming.

Finally, please include `readname/1` or `readname/2` on the WARNING line so one can `grep` for it.

**Comment by mmokrejs** [comment]
Or do you mean _Will discard this read pair_ will actually put it into `$prefix.se.fastq.gz` with the <21nt read discarded? ;-)

**Comment by jaredo** [comment]
>The second "WARNING" is more a surprise. Why don't you convert this read pair into a single-ended read instead?

I am assuming something like this has happened. Your original data looked like this

```
R1:
AAAAAXXXXXXXXXXXXXXXXX 
R2:
XXXXXXXXXXXXXXXXBBBBXX
```
where `AAAAA` is an external adapter you clipped with an external tool and `BBBB` is the junction adapter. So nxtrim gets the following:

```
R1:
XXXXXXXXXXXXXXXXX 
R2:
XXXXXXXXXXXXXXXXBBBBXX
```

this read is still salvageable as a MP so I don't see any reason to discard it. The warning is just there in case people run NxTrim twice on the same data.

>Also, it seems it complains about both input read <21nt and about such short reads after your trimming.

The error message is here:

https://github.com/sequencing/NxTrim/blob/master/matepair.cpp#L514-L526

this is before any trimming.

**Comment by jaredo** [comment]
Oh I see. You mean when R1 is 15bp and R2 is 150bp, I should put R2 into *.se.fastq.gz and just throw away R1 rather than the entire pair.

This is a good suggestion - although <21bp reads are pretty rare so it has never really come up.

**Comment by mmokrejs** [comment]
Yes, please fix that. Often after P1/P2 trimming you get very short reads.

So how about:
-WARNING: reads with differing lengths. Has this data already been trimmed?
+INFO: Reads with differing lengths. Hope you are not running nxtrim for second time on the same data.
