### ISSUE TITLE
FASTQ format is invalid

### ISSUE THREAD

**Issue by mmokrejs** [sequencing/NxTrim#40]
With version `v0.4.1-6d91d55` I ended up with broken FASTQ files. Seems some buffers are not flushed before another entry is printed out. Initially I saw some empty lines in the FASTQ file but later found even this, more problematic section.

```
nxtrim -s .7 -w -1 HFYJ5AFXX.4_5kb_R1.trimmomatic.SE.fastq -2 HFYJ5AFXX.4_5kb_R2.trimmomatic.SE.fastq -O HFYJ5AFXX.4_5kb.trimmomatic.nxtrim --separate --preserve-mp --rf

...

@NB501598:62:HFYJ5AFXX:4:11401:12431:3156 1:N:0:CTTGTA
AACCAGAAAAGTCTTGGAGAACAACGGAAGTGTATATTTGEE/EEE8A/EEEAEEEEEEEEEEE2ATTTEEEEEEAGGAGAGEEEE/EEEEEA/AEEEEECCGTTGCGT4CAATTAATCTGTATTTATATATAEEEEEEEEEETATAACTAAACAGC
+
AAAAAAEETFYJ5AFXX:4:11401:18721:2665 1:N:0:CTTGTA
TAAAACATGTATAAAATTAAAAGATTT1401:16TCACC/EEAA
@E<A
@NB501598:62:HFYJ5AFXX:4:11401:1:0:CTTG11401:G598:62:HFYJ5AFXX:4:11401:19143:3062 1:NT9C6TTTTATEAE/EEE75A:CTTGTA2CTCACTTTTATCTTTAATTTTGTTTTACACTGCTTAACATAACACAAAGTTGTTACC/EE6AAAEEEEEEEAEEEEEEEA/EEEEEEEAEEEEEEEA/EEEEEEEAEEEEEEEA/EE18510GGTCG11401:1E/EEEEAEAEAEEEAEAEAE/EAEEEEEEEEEEEA/EEACTCTTE/E/E/EE/EEE/E
@NB501598:62:HFYJ5AFXX:4:11401:10423:3041ATTAAC
+
6A981 1:N:0:CTTGTA
TATTTATCCTTAGTGTGATATTATCACGAA7767:ATTGTACTE/EEEEEEEEEEEE/E/EEEE/TTTATCCTTAGTGTGATATTATCACGAA7767:A0EEEAE/A/AATTAATCACA9EEE/EE928 1:NTCEEEEEEEE6EEEE/EAE/A/AATTAATCACA9EEE/EE928 1:NTCEEETTT1741598:62:CCTTTATAC
+
AA:25312:29862:HFYJ5AFXX:4:11401:6951:3071 1:N:0:CTFYJ5AFXX:4:1ACC
+
+
AAAAEEEEEEAEEEEEEEAEEEEEEEE598:62EEEAEE
7GCCAATAGTGTCAAAAAEEEEAAAAGTCCEEEEEE72 1:N90230:3TTAAGCAGCTGTTACAGTTTGCATAGCACGAEEEEETG
+

+
AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEETAEEEEEEEG6ACATGAAEEEEEAE/ET06TTTTCCTA1598:6230291598:62:HFYJ5AFXX:4:11401:10423:30ACATAGCA43:3062 1:NT9CATGTTAAAAA
+
6AAAAGG
+
AAAAAAAAAATCCTCCCCAGATAAAAEEEACGTTT464 CEAEEEE0:CTTGT6AAAT<ATAGGCCCACGACACCTE<EEEE:CTTGTTEEEEEEEEEEEEEEEEGG0G62 1:NT9CATGTTAAAAEEEAEEEEEEGTTAAAAEETAAAATGACGGTTTTTTTEEEEE
@NB501598:62:HFYJ5AFXX:4:1TE<EEEE:CTTGTAATTTGTCATTAAAATGTCAATAAGTGTAAGTTG1401:453:3041AGCTGTTACAC5A:CTTGTA2501598:TTAGGAGGGAEEEEEE/E/AE/E//EA/E/E/ECCTCTACATTTACAACATTTGTTGTGAGCTCCCTTTTGATTEEEEEE<//7TTT401:1E/EX:4:11401:11751:2968 1:N:0:CTTGTA
A987 1:NEEEEE
GTTTATTTTGTTTTACACTGCTTAACATAACACAAA98:62:HFYJ5AFXX:4CCATAACACAAA98:62:HFYJ5AFXX:4CCATAACAAGCGAGAGEEEEEEE1:15781:AEEEEEEEEEG1AAAAAAEEEEE3/GGCTCCCTGCGGAGGAAATGCTGTGTTEEEEEEEEEEEEEEEEAEEEEEEECCEEEEEE72 1:N9A/AATTAATC:N:0:CTTGTA
TGGACC11401:2336546:2522EEEEEEEEEEAE
@NB562:HFYJ5AFXX:4CCATAACAAGCGAGAGEEEEEEEEEEB50155TTA
A987 1:NEEEEE
ACTTAAAGTT0:CTTGTA
ATAGGAGG5AFXX:4:1EEEEEEEEEGAAGCGA/TGGA491:27X:4:110
+
AA/AA/3E6EEEAAEECGTAGTG3TTAAAAEETAAAATG5/ 1:N:0:CTTGTA
AAGAC91:2934 0:2829 TCTTGEEEEAE
@NB562:HF:3062 1EEEEEEE/A///E/GCACA:4CCATAACAAGCGAGAGEEEEEEEEEEB50155TTA
A9EEEEEEEEEEEEEEEEEEEEEEATAACTTGTA
:0:CTTCTTCTTCTTCTTCTTCTTAEAEEEEEEEEEEAEEEAE:62:HFYNB50/
7GCCAAT1598501598:62:HFYJ5AFXX:4:11401:22974:2707 1:NT2:HFYJ5AFXXA<AGTTACC//E////EEEECGTTACC//E////EEEEEEEEA/3A:62:HFYJ5AFXX:4:11401:5703:2971 1:N:0///E/511401:7646:3073 C30 1:N:3073 C30GEEEAEEEEEE<AEEAE</E/EE/EE/6EE6TEAE</E/TGATGATTEEEEEEEEEATGTGAATTCCT742EEEEEE0155T1GG5A5TTAAEEEEEET155T1GG5A5TTAAEE84EA/EEETCTTCTTAEA
```

**Comment by mmokrejs** [comment]
I tend to think the gzipped chunks were reordered. Provided the above shows the uncompressed FASTQ content is shuffled then at least the gzipped stream should be correct. But it is not. So, it seems the chunks were shuffled after gzipping. Only a few files were without gzip decompression error:

```
$ for f in *.mp.fastq.gz; do echo $f; gzip -dc $f > /dev/null; done
HFYJ5AFXX.1_5kb.trimmomatic.nxtrim_R1.mp.fastq.gz

gzip: HFYJ5AFXX.1_5kb.trimmomatic.nxtrim_R1.mp.fastq.gz: invalid compressed data--format violated
HFYJ5AFXX.1_5kb.trimmomatic.nxtrim_R2.mp.fastq.gz
HFYJ5AFXX.1_8kb.trimmomatic.nxtrim_R1.mp.fastq.gz

gzip: HFYJ5AFXX.1_8kb.trimmomatic.nxtrim_R1.mp.fastq.gz: decompression OK, trailing garbage ignored
HFYJ5AFXX.1_8kb.trimmomatic.nxtrim_R2.mp.fastq.gz

gzip: HFYJ5AFXX.1_8kb.trimmomatic.nxtrim_R2.mp.fastq.gz: invalid compressed data--format violated
HFYJ5AFXX.2_5kb.trimmomatic.nxtrim_R1.mp.fastq.gz

gzip: HFYJ5AFXX.2_5kb.trimmomatic.nxtrim_R1.mp.fastq.gz: invalid compressed data--format violated
HFYJ5AFXX.2_5kb.trimmomatic.nxtrim_R2.mp.fastq.gz
HFYJ5AFXX.2_8kb.trimmomatic.nxtrim_R1.mp.fastq.gz

gzip: HFYJ5AFXX.2_8kb.trimmomatic.nxtrim_R1.mp.fastq.gz: invalid compressed data--format violated
HFYJ5AFXX.2_8kb.trimmomatic.nxtrim_R2.mp.fastq.gz

gzip: HFYJ5AFXX.2_8kb.trimmomatic.nxtrim_R2.mp.fastq.gz: invalid compressed data--format violated
HFYJ5AFXX.3_5kb.trimmomatic.nxtrim_R1.mp.fastq.gz

gzip: HFYJ5AFXX.3_5kb.trimmomatic.nxtrim_R1.mp.fastq.gz: decompression OK, trailing garbage ignored
HFYJ5AFXX.3_5kb.trimmomatic.nxtrim_R2.mp.fastq.gz

gzip: HFYJ5AFXX.3_5kb.trimmomatic.nxtrim_R2.mp.fastq.gz: invalid compressed data--format violated
HFYJ5AFXX.3_8kb.trimmomatic.nxtrim_R1.mp.fastq.gz

gzip: HFYJ5AFXX.3_8kb.trimmomatic.nxtrim_R1.mp.fastq.gz: invalid compressed data--format violated
HFYJ5AFXX.3_8kb.trimmomatic.nxtrim_R2.mp.fastq.gz
HFYJ5AFXX.4_5kb.trimmomatic.nxtrim_R1.mp.fastq.gz

gzip: HFYJ5AFXX.4_5kb.trimmomatic.nxtrim_R1.mp.fastq.gz: invalid compressed data--format violated
HFYJ5AFXX.4_5kb.trimmomatic.nxtrim_R2.mp.fastq.gz
HFYJ5AFXX.4_8kb.trimmomatic.nxtrim_R1.mp.fastq.gz

gzip: HFYJ5AFXX.4_8kb.trimmomatic.nxtrim_R1.mp.fastq.gz: invalid compressed data--format violated
HFYJ5AFXX.4_8kb.trimmomatic.nxtrim_R2.mp.fastq.gz
$
```

Myabe the gzipped data were stored in wrong order in the filesystem? I cannot exclude that.

**Comment by jaredo** [comment]
Sorry - I will need a reproducible example. Running this command on your earlier test case seems fine:

```
./nxtrim -w -s .7 -1 example/HFYJ5AFXX.1_5kb_R1.missed.fastq.txt -2 example/HFYJ5AFXX.1_5kb_R2.missed.fastq.txt --separate --preserve-mp -O test
```

**Comment by mmokrejs** [comment]
Try some **large** example, so that whichever buffers are needed are get filled up.

**Comment by jaredo** [comment]
I have run in it on a 200MB E.coli example with no problems. (See `test/test.sh` for data locations)

```
../nxtrim -s .7 -w -1 $r1 -2 $r2 -O EcMG --justmp --separate
$ ls EcMG_*gz
EcMG_R1.mp.fastq.gz  EcMG_R1.unknown.fastq.gz  EcMG_R2.mp.fastq.gz  EcMG_R2.unknown.fastq.gz
joconnell@ubuntu:~/workspace/NxTrim/test$ for i in EcMG_R*.gz; do gzip -dc $i > /dev/null ;done
```

**Comment by jaredo** [comment]
This is potentially some interaction between trimmomatic output and nxtrim?

**Comment by mmokrejs** [comment]
The input from trimmomatic was fine. I looked for the first entry shown above and it was valid FASTQ.

After nxtrim I have in this particular case:

```
@NB501598:62:HFYJ5AFXX:4:11401:12431:3156 1:N:0:CTTGTA
AACCAGAAAAGTCTTGGAGAACAACGGAAGTGTATATTTGEE/EEE8A/EEEAEEEEEEEEEEE2ATTTEEEEEEAGGAGAGEEEE/EEEEEA/AEEEEECCGTTGCGT4CAATTAATCTGTATTTATATATAEEEEEEEEEETATAACTAAACAGC
```
Note that QUALs are appened after the sequence.

I tend to believe it is a filesystem issue (LustreFS, Linux 2.6.32-573.12.1.el6.noc0w.x86_64).

**Comment by jaredo** [comment]
Is it possible to output to local disk and see if the problem remains?

Sorry, there is not much I can do without a test case.

**Comment by mmokrejs** [comment]
I repeated that on local ext3 filesystem and again I get `invalid compressed data--format violated` from `gzip -dc`. Would you mind checking how nxtrim compressed the output streams? Something what could re-order the chunks? Provided the gzip chunk ordering is wrong then it does not make sense to look into the uncompressed FASTQ data whether it is valid or not. This basically narrows down the issue to something about the compression, the part outputting the FASTQ stream is probably fine.

I will re-try now without gzip compression using `--stdout`.
Meanwhile opened issue #41 as a feature request.

**Comment by mmokrejs** [comment]
> I will re-try now without gzip compression using --stdout.

The output seems OK, I successfully converted 2.GB FASTA to FASTA and indexed it using formatdb. But those are just mate pair reads, so this cannot reproduce the problem would your streams for say `mp`, `se` and `unknown` get mixed together in your code. I would say unless #41 is implemented I cannot test if nxtrim mixed up the separate streams or not.

**Comment by jaredo** [comment]
Note that `--stdout` is printing MP+unknown. You can  get *just MP* reads to stdout with `--stdout-mp` or *just unknown* with `--stdout-un`. I know this is separate to the problem being discussed here but seems relevant to your work.

I have just cleaned up the memory management in the last commit 4965b00. There was some redundant memory copying going on. I am not sure if it is related to your issue though.

FYI. I am not using any streams for the gzipped output. It is a simple application of `gzwrite()` from zlib. See:

https://github.com/sequencing/NxTrim/blob/master/fastqlib.cpp#L235-L244

**Comment by mmokrejs** [comment]
Thanks for clarification, good to know 2 streams are combined properly in the --stdout output.

I was so far at this last commit 6d91d5508f77af9e417bfc5391fd92cbfa468a44 , I will update now.

I also thought about aggressive CXXFLAGS (I used -O2 -march=native) which should be actually safe enough.

**Comment by mmokrejs** [comment]
Problem persists in compressed data.

**Comment by mmokrejs** [comment]
I compiled on the same host using older g++/libc/zlib and problem seems gone even when files stored on LustreFS. The "problematic" combination is:

```
[ebuild   R    ] sys-libs/zlib-1.2.11::gentoo  USE="minizip -static-libs" 0 KiB
[ebuild   R    ] sys-libs/glibc-2.24-r1:2.2::gentoo  USE="gd nscd rpc -audit -caps -debug (-hardened) (-multilib) -profile (-selinux) (-suid) -systemtap -vanilla" 66 KiB
[ebuild   R    ] sys-devel/gcc-4.9.4:4.9.4::gentoo  USE="cxx fortran nls nptl objc openmp sanitize vtv (-altivec) (-awt) -cilk -debug -doc (-fixed-point) -gcj -go -graphite (-hardened) (-libssp) (-multilib) -nopie -nossp -objc++ -objc-gc -regression-test (-vanilla)" 0 KiB
```


But inspecting http://www.zlib.net/ I feel more buggy are the previous zlib versions.

The working binary uses
```
-rwxr-xr-x 1 root root 88600 Feb 22  2013 /lib64/libz.so.1.2.3
-rwxr-xr-x 1 root root 1920936 Feb 16  2016 /lib64/libc-2.12.so
gcc-4.4.7
```

**Comment by jaredo** [comment]
Maybe switching to a static build in the Makefile will help?

**Comment by jaredo** [comment]
I think this is resolved.
