### ISSUE TITLE
ERROR: the --preserve_mp and --justmp flags are incompatible [question]

### ISSUE THREAD

**Issue by sjackman** [sequencing/NxTrim#50]
Does `--justmp` imply `--preserve_mp`? I'd like to write mate-pair and unknown reads to stdout. Even when the corresponding PE has longer reads, I'd like to output only the MP reads. Is it correct to use `nxtrim --stdout --justmp --rf`?

```sh
nxtrim --stdout --justmp --rf \
    -1 <(seqtk seq -1 dmelanogaster.mp.fq.gz) \
    -2 <(seqtk seq -2 dmelanogaster.mp.fq.gz) \
  | pigz -p16 >dmelanogaster.mp.nxtrim.fq.gz
```

**Comment by jaredo** [comment]
You want `--justmp` for your application, that just spits out mate-pair and unknown reads, it will also N-pad overly trimmed reads so that proper pairs are retained. You can actually just call `--stdout` as that automatically enables `--justmp`.

The `--preserve_mp` flag is more niche. It will try to output as many MPs as possible but will fallback to PE when an MP is impossible.

Here is an example showing the difference. When using `--justmp`/`--stdout` it just N pads the entire read. When turning on `--preserve_mp` it falls back to PE because there is no useable MP in that data.

```
##adapter is right at the start of read 1 so we cannot get any useable MP sequence
$ cat 1.fq
@M903:194:000000000-A5FBD:1:1108:18012:8206 1:N:0:CGATGT
TATAAGAGACAGGCAGAGCTTATGTAGTTAATGCCCGTTATAGGGGGGTGCTAATCTGGATCCCCTACCACCGAGCTGGGATGTATATTAGCTTGCTTGAACGCATCGCCGAACAACGCTAGATATCTCTTTGATTGCAGAGCAAGAGAGT
+
CCCDBFFFFFFFGGGGGGGGGGHHHHHHHHHHHHHHHHGGGGGHHHGGGGHHGGGGGGGHGGGGGGGHHHHHHHHHGGGGGGHGEGGGHGGGGGGGGHGHGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHH
$ cat 2.fq
@M903:194:000000000-A5FBD:1:1108:18012:8206 2:N:0:CGATGT
GTTCCACCGGAGCCGAGACTAAATAGTCTCGCCCCTTCCTGGTTACCGGCCTTCAATGTGTAGGAAGTAGCCTTGTCAGTAGACTCTGTATTCCTTATCACGACTAAATTGAGTACTTTGGTTTGCGATGCGCCGTACTTGGCATAGAAGT
+
CCCDBFFFFFFFGGGGGGGGGGHHHHHHHHHHHHHHHHGGGGGHHHGGGGHHGGGGGGGHGGGGGGGHHHHHHHHHGGGGGGHGEGGGHGGGGGGGGHGHGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHH
```

```
##we pad the whole of R1 so you maintain the DNA in R2 and also keep the proper pair
$ ./nxtrim -1 1.fq -2 2.fq --stdout 2> /dev/null
@M903:194:000000000-A5FBD:1:1108:18012:8206 1:N:0:CGATGT
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
+
#######################################################################################################################################################
@M903:194:000000000-A5FBD:1:1108:18012:8206 2:N:0:CGATGT
ACTTCTATGCCAAGTACGGCGCATCGCAAACCAAAGTACTCAATTTAGTCGTGATAAGGAATACAGAGTCTACTGACAAGGCTACTTCCTACACATTGAAGGCCGGTAACCAGGAAGGGGCGAGACTATTTAGTCTCGGCTCCGGTGGAAC
+
HHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGGHGHGGGGGGGGHGGGEGHGGGGGGHHHHHHHHHGGGGGGGHGGGGGGGHHGGGGHHHGGGGGHHHHHHHHHHHHHHHHGGGGGGGGGGFFFFFFFBDCCC
```

```
## here we are forced to keep the PE because there is no useable MP data.
$ ./nxtrim -1 1.fq -2 2.fq --preserve-mp -O test 2> /dev/null
$ gunzip -c test.pe.fastq.gz
@M903:194:000000000-A5FBD:1:1108:18012:8206 1:N:0:CGATGT
GCAGAGCTTATGTAGTTAATGCCCGTTATAGGGGGGTGCTAATCTGGATCCCCTACCACCGAGCTGGGATGTATATTAGCTTGCTTGAACGCATCGCCGAACAACGCTAGATATCTCTTTGATTGCAGAGCAAGAGAGT
+
GGGGGGGGGGHHHHHHHHHHHHHHHHGGGGGHHHGGGGHHGGGGGGGHGGGGGGGHHHHHHHHHGGGGGGHGEGGGHGGGGGGGGHGHGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHH
@M903:194:000000000-A5FBD:1:1108:18012:8206 2:N:0:CGATGT
GTTCCACCGGAGCCGAGACTAAATAGTCTCGCCCCTTCCTGGTTACCGGCCTTCAATGTGTAGGAAGTAGCCTTGTCAGTAGACTCTGTATTCCTTATCACGACTAAATTGAGTACTTTGGTTTGCGATGCGCCGTACTTGGCATAGAAGT
+
CCCDBFFFFFFFGGGGGGGGGGHHHHHHHHHHHHHHHHGGGGGHHHGGGGHHGGGGGGGHGGGGGGGHHHHHHHHHGGGGGGHGEGGGHGGGGGGGGHGHGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHH
```

**Comment by sjackman** [comment]
Thanks for the quick response, Jared. Let me check that I understand correctly:
If a read has both a usable paired-end and mate-pair read, and the paired-end read is longer…
+ with `--justmp` it outputs only the mate-pair read
+ with `--preserve-mp` it outputs only the mate-pair read
+ without `--preserve-mp` it outputs only the paired-end read
Is there any mode of operation that outputs both the paired-end and mate-pair reads?

**Comment by jaredo** [comment]
That is correct. "Usable" here means that there is at least `minlength` (default 21) bases to use on R1 and R2.

>Is there any mode of operation that outputs both the paired-end and mate-pair reads?

I don't have this. I was worried about creating redundant reads.  

In practice, I think `--justmp` is what most users want.  When we developed the tool (early 2014), SPAdes did not have official mate-pair support and we found arranging the reads into MP/PE/SE was quite helpful for Velvet. Nowadays, I just output MPs and assemble with SPAdes which makes very good use of MPs. [I did some benchmarking here](https://github.com/sequencing/NxTrim/wiki/Bacterial-assemblies-using-Nextera-Mate-pairs).

**Comment by sjackman** [comment]
`--justmp` is working great with ABySS. I'm assembling a Nextera Drosophila data set over at https://github.com/sjackman/abyss-drosophila-melanogaster
The initial assembly was poor because the Nextera library is 58% FR (42% RF), and ABySS currently goes with whichever orientation is in the majority, so it selected FR. Specifying on the command line that the library is RF oriented resolves the problem, but most users won't do that, and it's poorly documented how to do that. Using NxTrim reduces the FR proportion from 58% to 1.5%, and ABySS then detects that the library is RF oriented. ABySS actually works surprisingly well in this case if you specify that the library is RF oriented, even with 58% FR orientation; I hadn't expected that.

I want to set reasonable thresholds for ABySS. Currently >50% FR and the library is treated as FR. I'm thinking it should be something like >99% FR then the library is FR oriented. >x% RF then the library is RF oriented. Anywhere in between, print an error message and exit and tell the user to trim adapters with NxTrim. In your experience, whats'a good proportion of RF oriented reads for a Nextera mate-pair library?

The proportion of FR/RF reads is estimated by mapping reads to the initial de Bruijn Graph assembly, so is biased against the short FR fragments, so the estimate is not perfect.

I have an issue for ABySS open over at https://github.com/bcgsc/abyss/issues/164 @benvvalk

**Comment by jaredo** [comment]
Glad you are find it useful!

> In your experience, whats'a good proportion of RF oriented reads for a Nextera mate-pair library?

I think this varies a lot between labs. I took a quick look at some of our standard E.coli data (see below) and found 98.5% and 98.2% correctly orientated read pairs for the mp and unknown libraries respectively. Note that when we see an adapter we can guarantee (just about) that the read orientation is known ie. the MP class is very trustworthy. When we do not see an adapter (the unknown class) we cannot always guarantee the orientation and sometimes you will see a PE in there (so called MP contaminants). 

I do not see the latter occurring very frequently in my (fairly limited) data, but I am told it can happen with high frequency in some samples.

```

$ ../nxtrim -1 EcMG1_ATGTCA_L001_R1_001.fastq.gz -2 EcMG1_ATGTCA_L001_R2_001.fastq.gz --stdout-mp | bwa mem EcMG.fna - -p | gzip -1 > mp.sam.gz
$ ../nxtrim -1 EcMG1_ATGTCA_L001_R1_001.fastq.gz -2 EcMG1_ATGTCA_L001_R2_001.fastq.gz --stdout-un | bwa mem EcMG.fna - -p | gzip -1 > un.sam.gz

$ python ../scripts/count_orientation.py mp.sam.gz 
FR 394391
RF 1712
FF 2155
RR 2084

$ python ../scripts/count_orientation.py un.sam.gz 
FR 109543
RF 828
FF 664
RR 560
```

**Comment by sjackman** [comment]
After classification with NxTrim I see similar to you, >98% RF-oriented alignments. Before classification with NxTrim, if you map the raw reads to the reference using BWA-MEM, what's the proportion of RF-oriented reads to FR-reads for a typical library?

**Comment by jaredo** [comment]
```
$ bwa mem EcMG.fna  EcMG1_ATGTCA_L001_R1_001.fastq.gz EcMG1_ATGTCA_L001_R2_001.fastq.gz | gzip -1 > raw.sam.gz
$ python ../scripts/count_orientation.py raw.sam.gz
FR 340661
RF 473177
FF 5253
RR 5069
```

So I got 57% RF in that example.  Perhaps 90% is a sensible default value for AbySS, 99% is probably a bit too stringent.

**Comment by sjackman** [comment]
For a paired-end libraries, most libraries I have seen have >99% FR orientation (<1% RF orientation).
Are you saying that if the FR orientation is <90% (>10% RF orientation) assume that it's a mate-pair library?

**Comment by jaredo** [comment]
I think my suggestion is the same as yours: if the majority orientation (either RF or FR) occurs >x%, use that orientation, otherwise raise an error.  Where x is a parameter with a default like 90-99%.

We might be getting a bit confused because nxtrim by default reverse complements mate pairs such that they come out as FR (SPAdes/velvet like this), whereas by turning on `--rf` you are disabling that behaviour.

For example my command:
```
../nxtrim -1 EcMG1_ATGTCA_L001_R1_001.fastq.gz -2 EcMG1_ATGTCA_L001_R2_001.fastq.gz --stdout-mp
```
is reverse complementing the reads such that we see >98% FR, whereas this command:
```
../nxtrim -1 EcMG1_ATGTCA_L001_R1_001.fastq.gz -2 EcMG1_ATGTCA_L001_R2_001.fastq.gz --stdout-mp --rf
```
disables reverse complement so you got >98% RF.

I expect MP libraries to be a little less pure in terms of orientation than standard PEs hence the suggestion of a more liberal 90% threshold.

**Comment by sjackman** [comment]
After NxTrim has run, I expect the library to be just fine, in my experience. If the user runs ABySS on a library that has *not* had NxTrim run, I'd like ABySS to detect the orientation of the library correctly. The current threshold of 50% is not working, because some uncorrected libraries have RF orientation of less than 50%, and are incorrectly detected as FR, which results in a terrible assembly.

1. >99% FR orientation, the library is FR oriented
2. >x% RF orientation, the library is RF oriented
3. Otherwise, emit an error, and suggest that the user either run NxTrim or specify the desired orientation to ABySS

What should `x%` be, so that it passes for most typical Nextera mate-pair libraries that have *not* had NxTrim run on them?

**Comment by sjackman** [comment]
For comparison the current logic is

1. `>50%` FR orientation, the library is FR oriented
2 `>50%` RF orientation, the library is RF oriented.

**Comment by jaredo** [comment]
Maybe x=95% is a sensible default.  There might be other things besides lack of trimming causing this number to be low, but that still means the user needs to do additional QC work.
