### ISSUE TITLE
Does it detect Nextera XT DNA adapter as well?

### ISSUE THREAD

**Issue by stemangiola** [sequencing/NxTrim#53]
Hello,

does this algorithm detect Nextera **XT** DNA adapters as well?

For example I7_Primer_Nextera_XT_and_Nextera_Enrichment_N707 (source: https://github.com/BioInfoTools/BBMap/blob/master/resources/adapters.fa)

Thanks.

**Comment by jaredo** [comment]
Hi @stemangiola.

No, this tool is primarily for removing Nextera Mate Pair junction adapters and arranging the reads in a way suitable for assembly/alignment.  There is some basic support for removing external adapters when the DNA fragment template is shorter than 2x the read length and read 1 covers the read 2 external adapter (or vice versa).

There are a variety of general purpose trimmers you could use for external adapters, for example:

http://cutadapt.readthedocs.io/en/stable/guide.html
https://github.com/lh3/trimadap
http://www.usadellab.org/cms/?page=trimmomatic
https://github.com/relipmoc/skewer

cheers,

Jared
