### ISSUE TITLE
Mate pair SamplePrep V2

### ISSUE THREAD

**Issue by kokyriakidis** [sequencing/NxTrim#56]
Hi! Does it also work for non-Nextera MATE PAIR libraries such as Mate pair SamplePrep V2? They also have internal biotinylated adapters and are in RF orientation! Does NxTrim work in this case?

**Comment by jaredo** [comment]
I think these older kits do not have the junction adapter and hence would not need this sort of trimming.  

@olest do you know the answer to this?

**Comment by olest** [comment]
Yes, I think the V2 mate pairs don't have the adapter . You could check if your library contains it, the sequence is given here : https://github.com/sequencing/NxTrim/blob/master/docs/adapter_matching.md

**Comment by kokyriakidis** [comment]
Yes, they do not have the adapter.  So NxTrim cannot distinguish them into Mate pair, PE, unknown and SE? Should I do any extra prepossessing step apart from adapter trimming error-correction etc?

**Comment by jaredo** [comment]
>So NxTrim cannot distinguish them into Mate pair, PE, unknown and SE?

That is right, NxTrim is not appropriate for these data.

>Should I do any extra prepossessing step apart from adapter trimming error-correction etc?

I have not used these libraries before, but your suggestions sound correct.
